/**
 * Datos estáticos solo para regenerar supabase/setup_completo.sql (pnpm db:generate).
 * La app en runtime carga todo desde Supabase.
 */
import type { GroupLetter, Match } from '../src/types.ts'

export const GROUP_TEAMS: Record<GroupLetter, string[]> = {
  A: ['México', 'Sudáfrica', 'Rep. de Corea', 'República Checa'],
  B: ['Canadá', 'Catar', 'Suiza', 'Bosnia y Herzegovina'],
  C: ['Brasil', 'Marruecos', 'Haití', 'Escocia'],
  D: ['Estados Unidos', 'Paraguay', 'Australia', 'Turquía'],
  E: ['Alemania', 'Curazao', 'Costa de Marfil', 'Ecuador'],
  F: ['Países Bajos', 'Japón', 'Suecia', 'Túnez'],
  G: ['Bélgica', 'Egipto', 'RI de Irán', 'Nueva Zelanda'],
  H: ['España', 'Cabo Verde', 'Arabia Saudí', 'Uruguay'],
  I: ['Francia', 'Senegal', 'Irak', 'Noruega'],
  J: ['Argentina', 'Argelia', 'Austria', 'Jordania'],
  K: ['Portugal', 'Uzbekistán', 'Colombia', 'RD Congo'],
  L: ['Inglaterra', 'Croacia', 'Ghana', 'Panamá'],
}

/** Códigos ISO para flagcdn — usado al generar SQL de countries */
export const TEAM_FLAG_CODES: Record<string, string> = {
  México: 'mx',
  Sudáfrica: 'za',
  'Rep. de Corea': 'kr',
  'República de Corea': 'kr',
  'República Checa': 'cz',
  Canadá: 'ca',
  Catar: 'qa',
  Suiza: 'ch',
  'Bosnia y Herzegovina': 'ba',
  Brasil: 'br',
  Marruecos: 'ma',
  Haití: 'ht',
  Escocia: 'gb-sct',
  'Estados Unidos': 'us',
  Paraguay: 'py',
  Australia: 'au',
  Turquía: 'tr',
  Alemania: 'de',
  Curazao: 'cw',
  'Costa de Marfil': 'ci',
  Ecuador: 'ec',
  'Países Bajos': 'nl',
  Japón: 'jp',
  Suecia: 'se',
  Túnez: 'tn',
  Bélgica: 'be',
  Egipto: 'eg',
  'RI de Irán': 'ir',
  Irán: 'ir',
  'Nueva Zelanda': 'nz',
  España: 'es',
  'Arabia Saudí': 'sa',
  Uruguay: 'uy',
  'Cabo Verde': 'cv',
  Francia: 'fr',
  Senegal: 'sn',
  Irak: 'iq',
  Noruega: 'no',
  Argentina: 'ar',
  Argelia: 'dz',
  Austria: 'at',
  Jordania: 'jo',
  Portugal: 'pt',
  Uzbekistán: 'uz',
  Colombia: 'co',
  'RD Congo': 'cd',
  Inglaterra: 'gb-eng',
  Croacia: 'hr',
  Ghana: 'gh',
  Panamá: 'pa',
}

/** Calendario oficial FIFA — `time` en hora del Este (EE. UU.) */
export const MATCHES: Match[] = [
  { id: 1, date: '2026-06-11', dateLabel: 'Jueves 11 jun', time: '15:00', home: 'México', away: 'Sudáfrica', group: 'A', stage: 'group', venue: 'Estadio Ciudad de México' },
  { id: 2, date: '2026-06-11', dateLabel: 'Jueves 11 jun', time: '22:00', home: 'Rep. de Corea', away: 'República Checa', group: 'A', stage: 'group', venue: 'Estadio Guadalajara' },
  { id: 3, date: '2026-06-12', dateLabel: 'Viernes 12 jun', time: '15:00', home: 'Canadá', away: 'Bosnia y Herzegovina', group: 'B', stage: 'group', venue: 'Estadio Toronto' },
  { id: 4, date: '2026-06-12', dateLabel: 'Viernes 12 jun', time: '21:00', home: 'Estados Unidos', away: 'Paraguay', group: 'D', stage: 'group', venue: 'Estadio Los Ángeles' },
  { id: 5, date: '2026-06-13', dateLabel: 'Sábado 13 jun', time: '15:00', home: 'Catar', away: 'Suiza', group: 'B', stage: 'group', venue: 'Estadio Bahía de San Francisco' },
  { id: 6, date: '2026-06-13', dateLabel: 'Sábado 13 jun', time: '18:00', home: 'Brasil', away: 'Marruecos', group: 'C', stage: 'group', venue: 'Estadio Nueva York Nueva Jersey' },
  { id: 7, date: '2026-06-13', dateLabel: 'Sábado 13 jun', time: '21:00', home: 'Haití', away: 'Escocia', group: 'C', stage: 'group', venue: 'Estadio Boston' },
  { id: 8, date: '2026-06-14', dateLabel: 'Domingo 14 jun', time: '00:00', home: 'Australia', away: 'Turquía', group: 'D', stage: 'group', venue: 'Estadio BC Place Vancouver' },
  { id: 9, date: '2026-06-14', dateLabel: 'Domingo 14 jun', time: '13:00', home: 'Alemania', away: 'Curazao', group: 'E', stage: 'group', venue: 'Estadio Houston' },
  { id: 10, date: '2026-06-14', dateLabel: 'Domingo 14 jun', time: '16:00', home: 'Países Bajos', away: 'Japón', group: 'F', stage: 'group', venue: 'Estadio Dallas' },
  { id: 11, date: '2026-06-14', dateLabel: 'Domingo 14 jun', time: '19:00', home: 'Costa de Marfil', away: 'Ecuador', group: 'E', stage: 'group', venue: 'Estadio Filadelfia' },
  { id: 12, date: '2026-06-14', dateLabel: 'Domingo 14 jun', time: '22:00', home: 'Suecia', away: 'Túnez', group: 'F', stage: 'group', venue: 'Estadio Monterrey' },
  { id: 13, date: '2026-06-15', dateLabel: 'Lunes 15 jun', time: '12:00', home: 'España', away: 'Cabo Verde', group: 'H', stage: 'group', venue: 'Estadio Atlanta' },
  { id: 14, date: '2026-06-15', dateLabel: 'Lunes 15 jun', time: '15:00', home: 'Bélgica', away: 'Egipto', group: 'G', stage: 'group', venue: 'Estadio Seattle' },
  { id: 15, date: '2026-06-15', dateLabel: 'Lunes 15 jun', time: '18:00', home: 'Arabia Saudí', away: 'Uruguay', group: 'H', stage: 'group', venue: 'Estadio Miami' },
  { id: 16, date: '2026-06-15', dateLabel: 'Lunes 15 jun', time: '21:00', home: 'RI de Irán', away: 'Nueva Zelanda', group: 'G', stage: 'group', venue: 'Estadio Los Ángeles' },
  { id: 17, date: '2026-06-16', dateLabel: 'Martes 16 jun', time: '15:00', home: 'Francia', away: 'Senegal', group: 'I', stage: 'group', venue: 'Estadio Nueva York Nueva Jersey' },
  { id: 18, date: '2026-06-16', dateLabel: 'Martes 16 jun', time: '18:00', home: 'Irak', away: 'Noruega', group: 'I', stage: 'group', venue: 'Estadio Boston' },
  { id: 19, date: '2026-06-16', dateLabel: 'Martes 16 jun', time: '21:00', home: 'Argentina', away: 'Argelia', group: 'J', stage: 'group', venue: 'Estadio Kansas City' },
  { id: 20, date: '2026-06-17', dateLabel: 'Miércoles 17 jun', time: '00:00', home: 'Austria', away: 'Jordania', group: 'J', stage: 'group', venue: 'Estadio Bahía de San Francisco' },
  { id: 21, date: '2026-06-17', dateLabel: 'Miércoles 17 jun', time: '13:00', home: 'Portugal', away: 'RD Congo', group: 'K', stage: 'group', venue: 'Estadio Houston' },
  { id: 22, date: '2026-06-17', dateLabel: 'Miércoles 17 jun', time: '16:00', home: 'Inglaterra', away: 'Croacia', group: 'L', stage: 'group', venue: 'Estadio Dallas' },
  { id: 23, date: '2026-06-17', dateLabel: 'Miércoles 17 jun', time: '19:00', home: 'Ghana', away: 'Panamá', group: 'L', stage: 'group', venue: 'Estadio Toronto' },
  { id: 24, date: '2026-06-17', dateLabel: 'Miércoles 17 jun', time: '22:00', home: 'Uzbekistán', away: 'Colombia', group: 'K', stage: 'group', venue: 'Estadio Ciudad de México' },
  { id: 25, date: '2026-06-18', dateLabel: 'Jueves 18 jun', time: '12:00', home: 'República Checa', away: 'Sudáfrica', group: 'A', stage: 'group', venue: 'Estadio Atlanta' },
  { id: 26, date: '2026-06-18', dateLabel: 'Jueves 18 jun', time: '15:00', home: 'Suiza', away: 'Bosnia y Herzegovina', group: 'B', stage: 'group', venue: 'Estadio Los Ángeles' },
  { id: 27, date: '2026-06-18', dateLabel: 'Jueves 18 jun', time: '18:00', home: 'Canadá', away: 'Catar', group: 'B', stage: 'group', venue: 'Estadio BC Place Vancouver' },
  { id: 28, date: '2026-06-18', dateLabel: 'Jueves 18 jun', time: '21:00', home: 'México', away: 'Rep. de Corea', group: 'A', stage: 'group', venue: 'Estadio Guadalajara' },
  { id: 29, date: '2026-06-19', dateLabel: 'Viernes 19 jun', time: '15:00', home: 'Estados Unidos', away: 'Australia', group: 'D', stage: 'group', venue: 'Estadio Seattle' },
  { id: 30, date: '2026-06-19', dateLabel: 'Viernes 19 jun', time: '18:00', home: 'Escocia', away: 'Marruecos', group: 'C', stage: 'group', venue: 'Estadio Boston' },
  { id: 31, date: '2026-06-19', dateLabel: 'Viernes 19 jun', time: '21:00', home: 'Brasil', away: 'Haití', group: 'C', stage: 'group', venue: 'Estadio Filadelfia' },
  { id: 32, date: '2026-06-20', dateLabel: 'Sábado 20 jun', time: '00:00', home: 'Turquía', away: 'Paraguay', group: 'D', stage: 'group', venue: 'Estadio Bahía de San Francisco' },
  { id: 33, date: '2026-06-20', dateLabel: 'Sábado 20 jun', time: '13:00', home: 'Países Bajos', away: 'Suecia', group: 'F', stage: 'group', venue: 'Estadio Houston' },
  { id: 34, date: '2026-06-20', dateLabel: 'Sábado 20 jun', time: '16:00', home: 'Alemania', away: 'Costa de Marfil', group: 'E', stage: 'group', venue: 'Estadio Toronto' },
  { id: 35, date: '2026-06-20', dateLabel: 'Sábado 20 jun', time: '22:00', home: 'Ecuador', away: 'Curazao', group: 'E', stage: 'group', venue: 'Estadio Kansas City' },
  { id: 36, date: '2026-06-21', dateLabel: 'Domingo 21 jun', time: '00:00', home: 'Túnez', away: 'Japón', group: 'F', stage: 'group', venue: 'Estadio Monterrey' },
  { id: 37, date: '2026-06-21', dateLabel: 'Domingo 21 jun', time: '12:00', home: 'España', away: 'Arabia Saudí', group: 'H', stage: 'group', venue: 'Estadio Atlanta' },
  { id: 38, date: '2026-06-21', dateLabel: 'Domingo 21 jun', time: '15:00', home: 'Bélgica', away: 'RI de Irán', group: 'G', stage: 'group', venue: 'Estadio Los Ángeles' },
  { id: 39, date: '2026-06-21', dateLabel: 'Domingo 21 jun', time: '18:00', home: 'Uruguay', away: 'Cabo Verde', group: 'H', stage: 'group', venue: 'Estadio Miami' },
  { id: 40, date: '2026-06-21', dateLabel: 'Domingo 21 jun', time: '21:00', home: 'Nueva Zelanda', away: 'Egipto', group: 'G', stage: 'group', venue: 'Estadio BC Place Vancouver' },
  { id: 41, date: '2026-06-22', dateLabel: 'Lunes 22 jun', time: '13:00', home: 'Argentina', away: 'Austria', group: 'J', stage: 'group', venue: 'Estadio Dallas' },
  { id: 42, date: '2026-06-22', dateLabel: 'Lunes 22 jun', time: '17:00', home: 'Francia', away: 'Irak', group: 'I', stage: 'group', venue: 'Estadio Filadelfia' },
  { id: 43, date: '2026-06-22', dateLabel: 'Lunes 22 jun', time: '20:00', home: 'Noruega', away: 'Senegal', group: 'I', stage: 'group', venue: 'Estadio Nueva York Nueva Jersey' },
  { id: 44, date: '2026-06-23', dateLabel: 'Martes 23 jun', time: '23:00', home: 'Jordania', away: 'Argelia', group: 'J', stage: 'group', venue: 'Estadio Bahía de San Francisco' },
  { id: 45, date: '2026-06-23', dateLabel: 'Martes 23 jun', time: '13:00', home: 'Portugal', away: 'Uzbekistán', group: 'K', stage: 'group', venue: 'Estadio Houston' },
  { id: 46, date: '2026-06-23', dateLabel: 'Martes 23 jun', time: '16:00', home: 'Inglaterra', away: 'Ghana', group: 'L', stage: 'group', venue: 'Estadio Boston' },
  { id: 47, date: '2026-06-23', dateLabel: 'Martes 23 jun', time: '19:00', home: 'Panamá', away: 'Croacia', group: 'L', stage: 'group', venue: 'Estadio Toronto' },
  { id: 48, date: '2026-06-23', dateLabel: 'Martes 23 jun', time: '22:00', home: 'Colombia', away: 'RD Congo', group: 'K', stage: 'group', venue: 'Estadio Guadalajara' },
  { id: 49, date: '2026-06-24', dateLabel: 'Miércoles 24 jun', time: '15:00', home: 'Suiza', away: 'Canadá', group: 'B', stage: 'group', venue: 'Estadio BC Place Vancouver' },
  { id: 50, date: '2026-06-24', dateLabel: 'Miércoles 24 jun', time: '15:00', home: 'Bosnia y Herzegovina', away: 'Catar', group: 'B', stage: 'group', venue: 'Estadio Seattle' },
  { id: 51, date: '2026-06-24', dateLabel: 'Miércoles 24 jun', time: '18:00', home: 'Escocia', away: 'Brasil', group: 'C', stage: 'group', venue: 'Estadio Miami' },
  { id: 52, date: '2026-06-24', dateLabel: 'Miércoles 24 jun', time: '18:00', home: 'Marruecos', away: 'Haití', group: 'C', stage: 'group', venue: 'Estadio Atlanta' },
  { id: 53, date: '2026-06-24', dateLabel: 'Miércoles 24 jun', time: '21:00', home: 'República Checa', away: 'México', group: 'A', stage: 'group', venue: 'Estadio Ciudad de México' },
  { id: 54, date: '2026-06-24', dateLabel: 'Miércoles 24 jun', time: '21:00', home: 'Sudáfrica', away: 'Rep. de Corea', group: 'A', stage: 'group', venue: 'Estadio Monterrey' },
  { id: 55, date: '2026-06-25', dateLabel: 'Jueves 25 jun', time: '16:00', home: 'Curazao', away: 'Costa de Marfil', group: 'E', stage: 'group', venue: 'Estadio Filadelfia' },
  { id: 56, date: '2026-06-25', dateLabel: 'Jueves 25 jun', time: '16:00', home: 'Ecuador', away: 'Alemania', group: 'E', stage: 'group', venue: 'Estadio Nueva York Nueva Jersey' },
  { id: 57, date: '2026-06-25', dateLabel: 'Jueves 25 jun', time: '19:00', home: 'Japón', away: 'Suecia', group: 'F', stage: 'group', venue: 'Estadio Dallas' },
  { id: 58, date: '2026-06-25', dateLabel: 'Jueves 25 jun', time: '19:00', home: 'Túnez', away: 'Países Bajos', group: 'F', stage: 'group', venue: 'Estadio Kansas City' },
  { id: 59, date: '2026-06-25', dateLabel: 'Jueves 25 jun', time: '22:00', home: 'Turquía', away: 'Estados Unidos', group: 'D', stage: 'group', venue: 'Estadio Los Ángeles' },
  { id: 60, date: '2026-06-25', dateLabel: 'Jueves 25 jun', time: '22:00', home: 'Paraguay', away: 'Australia', group: 'D', stage: 'group', venue: 'Estadio Bahía de San Francisco' },
  { id: 61, date: '2026-06-26', dateLabel: 'Viernes 26 jun', time: '15:00', home: 'Noruega', away: 'Francia', group: 'I', stage: 'group', venue: 'Estadio Boston' },
  { id: 62, date: '2026-06-26', dateLabel: 'Viernes 26 jun', time: '15:00', home: 'Senegal', away: 'Irak', group: 'I', stage: 'group', venue: 'Estadio Toronto' },
  { id: 63, date: '2026-06-26', dateLabel: 'Viernes 26 jun', time: '20:00', home: 'Cabo Verde', away: 'Arabia Saudí', group: 'H', stage: 'group', venue: 'Estadio Houston' },
  { id: 64, date: '2026-06-26', dateLabel: 'Viernes 26 jun', time: '20:00', home: 'Uruguay', away: 'España', group: 'H', stage: 'group', venue: 'Estadio Guadalajara' },
  { id: 65, date: '2026-06-26', dateLabel: 'Viernes 26 jun', time: '23:00', home: 'Egipto', away: 'RI de Irán', group: 'G', stage: 'group', venue: 'Estadio Seattle' },
  { id: 66, date: '2026-06-26', dateLabel: 'Viernes 26 jun', time: '23:00', home: 'Nueva Zelanda', away: 'Bélgica', group: 'G', stage: 'group', venue: 'Estadio BC Place Vancouver' },
  { id: 67, date: '2026-06-27', dateLabel: 'Sábado 27 jun', time: '17:00', home: 'Panamá', away: 'Inglaterra', group: 'L', stage: 'group', venue: 'Estadio Nueva York Nueva Jersey' },
  { id: 68, date: '2026-06-27', dateLabel: 'Sábado 27 jun', time: '17:00', home: 'Croacia', away: 'Ghana', group: 'L', stage: 'group', venue: 'Estadio Filadelfia' },
  { id: 69, date: '2026-06-27', dateLabel: 'Sábado 27 jun', time: '19:30', home: 'Colombia', away: 'Portugal', group: 'K', stage: 'group', venue: 'Estadio Miami' },
  { id: 70, date: '2026-06-27', dateLabel: 'Sábado 27 jun', time: '19:30', home: 'RD Congo', away: 'Uzbekistán', group: 'K', stage: 'group', venue: 'Estadio Atlanta' },
  { id: 71, date: '2026-06-27', dateLabel: 'Sábado 27 jun', time: '22:00', home: 'Argelia', away: 'Austria', group: 'J', stage: 'group', venue: 'Estadio Kansas City' },
  { id: 72, date: '2026-06-27', dateLabel: 'Sábado 27 jun', time: '22:00', home: 'Jordania', away: 'Argentina', group: 'J', stage: 'group', venue: 'Estadio Dallas' },
  // Dieciseisavos — cruces confirmados; `time` en hora del Este (EE. UU.)
  { id: 73, date: '2026-06-28', dateLabel: 'Domingo 28 jun', time: '15:00', home: 'Sudáfrica', away: 'Canadá', stage: 'round32', venue: 'Estadio Los Ángeles' },
  { id: 74, date: '2026-06-29', dateLabel: 'Lunes 29 jun', time: '16:30', home: 'Alemania', away: 'Paraguay', stage: 'round32', venue: 'Estadio Boston' },
  { id: 75, date: '2026-06-29', dateLabel: 'Lunes 29 jun', time: '21:00', home: 'Países Bajos', away: 'Marruecos', stage: 'round32', venue: 'Estadio Monterrey' },
  { id: 76, date: '2026-06-29', dateLabel: 'Lunes 29 jun', time: '13:00', home: 'Brasil', away: 'Japón', stage: 'round32', venue: 'Estadio Houston' },
  { id: 77, date: '2026-06-30', dateLabel: 'Martes 30 jun', time: '17:00', home: 'Francia', away: 'Suecia', stage: 'round32', venue: 'Estadio Nueva York Nueva Jersey' },
  { id: 78, date: '2026-06-30', dateLabel: 'Martes 30 jun', time: '13:00', home: 'Costa de Marfil', away: 'Noruega', stage: 'round32', venue: 'Estadio Dallas' },
  { id: 79, date: '2026-06-30', dateLabel: 'Martes 30 jun', time: '21:00', home: 'México', away: 'Ecuador', stage: 'round32', venue: 'Estadio Ciudad de México' },
  { id: 80, date: '2026-07-01', dateLabel: 'Miércoles 1 jul', time: '12:00', home: 'Inglaterra', away: 'RD Congo', stage: 'round32', venue: 'Estadio Atlanta' },
  { id: 81, date: '2026-07-01', dateLabel: 'Miércoles 1 jul', time: '20:00', home: 'Estados Unidos', away: 'Bosnia y Herzegovina', stage: 'round32', venue: 'Estadio Bahía de San Francisco' },
  { id: 82, date: '2026-07-01', dateLabel: 'Miércoles 1 jul', time: '16:00', home: 'Bélgica', away: 'Senegal', stage: 'round32', venue: 'Estadio Seattle' },
  { id: 83, date: '2026-07-02', dateLabel: 'Jueves 2 jul', time: '19:00', home: 'Portugal', away: 'Croacia', stage: 'round32', venue: 'Estadio Toronto' },
  { id: 84, date: '2026-07-02', dateLabel: 'Jueves 2 jul', time: '15:00', home: 'España', away: 'Austria', stage: 'round32', venue: 'Estadio Los Ángeles' },
  { id: 85, date: '2026-07-02', dateLabel: 'Jueves 2 jul', time: '23:00', home: 'Suiza', away: 'Argelia', stage: 'round32', venue: 'Estadio BC Place Vancouver' },
  { id: 86, date: '2026-07-03', dateLabel: 'Viernes 3 jul', time: '18:00', home: 'Argentina', away: 'Cabo Verde', stage: 'round32', venue: 'Estadio Miami' },
  { id: 87, date: '2026-07-03', dateLabel: 'Viernes 3 jul', time: '21:30', home: 'Colombia', away: 'Ghana', stage: 'round32', venue: 'Estadio Kansas City' },
  { id: 88, date: '2026-07-03', dateLabel: 'Viernes 3 jul', time: '14:00', home: 'Australia', away: 'Egipto', stage: 'round32', venue: 'Estadio Dallas' },
  { id: 89, date: '2026-07-04', dateLabel: 'Sábado 4 jul', time: '20:00', home: 'Ganador P74', away: 'Ganador P77', stage: 'round16', venue: 'Estadio Filadelfia' },
  { id: 90, date: '2026-07-04', dateLabel: 'Sábado 4 jul', time: '16:00', home: 'Ganador P73', away: 'Ganador P75', stage: 'round16', venue: 'Estadio Houston' },
  { id: 91, date: '2026-07-05', dateLabel: 'Domingo 5 jul', time: '19:00', home: 'Ganador P76', away: 'Ganador P78', stage: 'round16', venue: 'Estadio Nueva York Nueva Jersey' },
  { id: 92, date: '2026-07-05', dateLabel: 'Lunes 6 jul', time: '23:00', home: 'Ganador P79', away: 'Ganador P80', stage: 'round16', venue: 'Estadio Ciudad de México' },
  { id: 93, date: '2026-07-06', dateLabel: 'Lunes 6 jul', time: '18:00', home: 'Ganador P83', away: 'Ganador P84', stage: 'round16', venue: 'Estadio Dallas' },
  { id: 94, date: '2026-07-06', dateLabel: 'Martes 7 jul', time: '23:00', home: 'Ganador P81', away: 'Ganador P82', stage: 'round16', venue: 'Estadio Seattle' },
  { id: 95, date: '2026-07-07', dateLabel: 'Martes 7 jul', time: '15:00', home: 'Ganador P86', away: 'Ganador P88', stage: 'round16', venue: 'Estadio Atlanta' },
  { id: 96, date: '2026-07-07', dateLabel: 'Martes 7 jul', time: '19:00', home: 'Ganador P85', away: 'Ganador P87', stage: 'round16', venue: 'Estadio BC Place Vancouver' },
  { id: 97, date: '2026-07-09', dateLabel: 'Jueves 9 jul', time: '19:00', home: 'Ganador P89', away: 'Ganador P90', stage: 'quarter', venue: 'Estadio Boston' },
  { id: 98, date: '2026-07-10', dateLabel: 'Viernes 10 jul', time: '18:00', home: 'Ganador P93', away: 'Ganador P94', stage: 'quarter', venue: 'Estadio Los Ángeles' },
  { id: 99, date: '2026-07-11', dateLabel: 'Sábado 11 jul', time: '20:00', home: 'Ganador P91', away: 'Ganador P92', stage: 'quarter', venue: 'Estadio Miami' },
  { id: 100, date: '2026-07-12', dateLabel: 'Domingo 12 jul', time: '00:00', home: 'Ganador P95', away: 'Ganador P96', stage: 'quarter', venue: 'Estadio Kansas City' },
  { id: 101, date: '2026-07-14', dateLabel: 'Martes 14 jul', time: '19:00', home: 'Ganador P97', away: 'Ganador P98', stage: 'semi', venue: 'Estadio Dallas' },
  { id: 102, date: '2026-07-15', dateLabel: 'Miércoles 15 jul', time: '19:00', home: 'Ganador P99', away: 'Ganador P100', stage: 'semi', venue: 'Estadio Atlanta' },
  { id: 103, date: '2026-07-18', dateLabel: 'Sábado 18 jul', time: '20:00', home: 'Perdedor P101', away: 'Perdedor P102', stage: 'third', venue: 'Estadio Miami' },
  { id: 104, date: '2026-07-19', dateLabel: 'Domingo 19 jul', time: '18:00', home: 'Ganador P101', away: 'Ganador P102', stage: 'final', venue: 'Estadio Nueva York Nueva Jersey' },
]
